# Generated by Django 4.2.7 on 2023-12-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('5-aside', '5-aside'), ('6-aside', '6-aside'), ('7-aside', '7-aside'), ('8-aside', '8-aside'), ('9-aside', '9-aside'), ('10-aside', '10-aside'), ('11-aside', '11-aside')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venues')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venues')),
            ],
        ),
        migrations.CreateModel(
            name='VenueFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField()),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venues')),
            ],
        ),
    ]
