# Generated by Django 4.2.7 on 2023-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venueprice_venueimages_venuefacilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='venue_status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=20),
        ),
    ]
