# Generated by Django 4.2.7 on 2023-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_alter_venues_venue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueprice',
            old_name='price',
            new_name='day_price',
        ),
        migrations.AddField(
            model_name='venueprice',
            name='night_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
