# Generated by Django 4.2.7 on 2023-12-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_rename_price_venueprice_day_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venues',
            name='address',
        ),
    ]
