# Generated by Django 4.2.7 on 2023-12-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_venues_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
