# Generated by Django 4.2.7 on 2023-12-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_venues_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimages',
            name='image',
            field=models.ImageField(null=True, upload_to='venue_images/'),
        ),
        migrations.AlterField(
            model_name='venues',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venues',
            name='venue_status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=20),
        ),
    ]
