# Generated by Django 4.2.7 on 2023-12-25 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0007_alter_venueimages_image_alter_venues_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuefacilities',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_facilities', to='venues.venues'),
        ),
        migrations.AlterField(
            model_name='venueimages',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_images', to='venues.venues'),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_prices', to='venues.venues'),
        ),
        migrations.CreateModel(
            name='VenueBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_status', models.BooleanField()),
                ('booking_status', models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to=settings.AUTH_USER_MODEL)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to='venues.venues')),
            ],
        ),
    ]
