# Generated by Django 4.2.7 on 2023-12-26 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_alter_venuebookings_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebookings',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venuebookings',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
    ]
