# Generated by Django 4.2.7 on 2023-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_venuebookings_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuebookings',
            name='booking_status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('booked', 'booked')], default='requested', max_length=20),
        ),
    ]
