# Generated by Django 4.2.7 on 2024-01-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_alter_venuebookings_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuebookings',
            name='payment_method',
        ),
    ]
