# Generated by Django 4.2.7 on 2023-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_registration_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
