# Generated by Django 4.2.7 on 2023-12-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_razorpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RazorPayment',
        ),
    ]
