# Generated by Django 4.2.7 on 2024-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_razorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
    ]
