# Generated by Django 4.2.7 on 2024-01-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, default='abc@gmail.com', max_length=100, null=True),
        ),
    ]
