# Generated by Django 4.2.7 on 2024-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('amateur', 'amateur'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('professional', 'professional')], default='beginner', max_length=50),
        ),
    ]
