# Generated by Django 4.2.7 on 2024-01-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_usernotification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
