# Generated by Django 4.2.7 on 2023-11-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='owner_phone_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
