# Generated by Django 4.2.7 on 2024-01-08 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0012_remove_venuebookings_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField()),
                ('min_skill', models.CharField(blank=True, choices=[('beginner', 'beginner'), ('amateur', 'amateur'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('professional', 'professional')], max_length=20, null=True)),
                ('max_skill', models.CharField(blank=True, choices=[('beginner', 'beginner'), ('amateur', 'amateur'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('professional', 'professional')], max_length=20, null=True)),
                ('description', models.TextField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='venues.venuebookings')),
                ('host_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
