# Generated by Django 4.2.7 on 2024-01-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergames',
            name='joined_players',
            field=models.IntegerField(default=1),
        ),
    ]
