# Generated by Django 4.2.7 on 2024-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_usergames_joined_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameusers',
            name='game_status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('removed', 'removed'), ('left', 'left')], default='requested', max_length=50),
        ),
    ]
