# Generated by Django 4.2.7 on 2024-01-08 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameusers_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameusers',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
