# Generated by Django 4.2.7 on 2024-01-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameusers_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergames',
            name='game_name',
            field=models.CharField(default="None's game", max_length=100),
        ),
    ]
