# Generated by Django 4.2.7 on 2024-01-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_usergames_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergames',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
